### PR TITLE
Aroiaaltuna rev

### PR DESCRIPTION
**Pull request by aroiaaltuna**
My contributions include revising the texts, correcting grammar and spelling mistakes, adding internal and external links and, finally, adding other media, such as appropriate images or YouTube videos. 

Isuue #13 
The group that created the content: @MSGW2018/group6

### CODE REVIEW

**Comment by aroiaaltuna** [comment]
I have deleted two files in journalism that I didn't want to. So, please, don't take into account the changes made in Journalism for the master branch.

**Review by mirenbz — APPROVED** [review]
There are some conflicts with this revision because there is already a revision by a classmate merged to `master`. I will try to add all your modifications so that nothing is lost, then merge.

**Comment by mirenbz** [comment]
Finally managed to merge with `master` through some hard manual work :muscle: 

Done in commit fa7592a, closes #13.

**Comment by mirenbz** [comment]
This revision is now merged into `master`. If any of you wants to add further modifications to the content, make sure you do so by editing the `master` branch.

**Comment by aroiaaltuna** [comment]
@mberasategi I did modifications in three "education" files: future, limitations and open education global conference.

**Pull request closed without merging**
