### PR TITLE
Introduction to identity construction

### PR DESCRIPTION
**Pull request by nataliaruizt**
This pull request is to merge the introduction to the master branch. We have written the main idea of what online identity construction is and we will work further on the two subtopics: online reputation and digital identity.

Feel free to comment us on what your thoughts are about our topic, we will be pleased to hear what you think. Thank you :octocat:

### CODE REVIEW

**Comment by aitorxagar** [comment]
:dancer:

**Comment by mberasategi** [comment]
Great! One last thing before we merge this first step. Remember to follow file naming conventions (lowercase only, and most importantly no spaces or special characters) for your file names.

**Comment by laidasalsamendi** [comment]
:octocat: cool

**Comment by aitorxagar** [comment]
💃

**Comment by mberasategi** [comment]
Approved. Corrected the `folder` name (it needs to be descriptive, because it will be along with the rest of the folders by the other teams when we merge to `master`) and added the links in the README. Merging.

**Pull request merged**
