### PR TITLE
We are going to work on journalism

### PR DESCRIPTION
**Pull request by GaraziArregui**
#JOURNALISM
##Subsections
###Functions of a good journalist
###Responsibilities
###Changes in the trade with the arrival of technology
###The future of journalism

### CODE REVIEW

**Comment by aroiaaltuna** [comment]
Today we have created a pull request and we have decided to divide our topic into four subsections.

**Comment by mberasategi** [comment]
Well done. However your links in the `README.md` file are not working...

**Comment by mberasategi** [comment]
Check my commit ↗️  I did two different changes to correct **only the first link** in your `README.md` file. Just do the same for the rest! (Note: you may have problems to do these changes in a Windows computer, so try with a Mac instead -- can't remember if you had one in your group or not. Let me know otherwhise!)

**Comment by mberasategi** [comment]
I deleted the unnecessary `.DS_Store` files and the duplicated files with different case. This is now ready to merge.

**Pull request merged**
